/******************************************************************************
**
**								Copyright (C) 2015  
**				Smartauto(China) Automotive Information System Co.,Ltd.
**								All rights reserved.
**
**----------------------------------File Info----------------------------------
**
**	Filename:		ApuRSetting.h
**	Abstract:		APUR_GID_SETTING
**	Creat By:		Zeno Liu
**	Creat Time:		2015.05.11
**	Version:		v1.0
**
******************************************************************************/

#ifndef	__APU_R_SETTING_H__
#define	__APU_R_SETTING_H__

/* \brief
	APUR_GID_SETTING sub id
*/
typedef enum
{
	APUR_SET_AUDIO				=0x01,
	APUR_SET_6CH_VOL,
	APUR_SET_GENERAL,
	APUR_SET_ASP,
	APUR_SET_GEQ,
	APUR_SET_PEQ,
	APUR_SET_RDS,
	APUR_SET_CH_GAIN,
	APUR_SET_SCREEN,
	APUR_SET_TUNER_FREQ
}enumApurSetting;

/* \brief
	APUR_SET_GENERAL
*/
typedef enum
{
	APUR_SET_GENERAL_RADIO_AREA,
	APUR_SET_GENERAL_LOAD_FACTORY_SUPPER_RESET,
	APUR_SET_GENERAL_AUXIN_VIDEO_FORMAT,
	APUR_SET_GENERAL_OPEN_LCD,
	APUR_SET_GENERAL_CLOCK_MODE,
	APUR_SET_GENERAL_CLOCK_HOUR,
	APUR_SET_GENERAL_CLOCK_MINUTE,
	APUR_SET_GENERAL_CAMERA_MIRROR_MODE,
	APUR_SET_GENERAL_RDS_CT_SET,
	APUR_SET_GENERAL_CAN_BRIGHT_ON,
	APUR_SET_GENERAL_CAN_BACK_LIGHT_LEVEL,
	APUR_SET_GENERAL_BEEP_TYPE_SWITCH,
	APUR_SET_GENERAL_EXTERNAL_TEL_MUTE_SWITCH,
	APUR_SET_GENERAL_EXTERNAL_SPEAKER_SET,
	APUR_SET_GENERAL_AUXIN_SWITCH_SET,
	APUR_SET_GENERAL_CAMERA_ONOFF,
	APUR_SET_GENERAL_AUTO_DIMMER,
	APUR_SET_GENERAL_AUXIN_SOURCE_TYPE,
	APUR_SET_GENERAL_KEY_COLOR_SET,
	APUR_SET_GENERAL_NAVI_VOICE_GUIDANCE_MODE_SET,
	APUR_SET_GENERAL_ACTIVE_SOUND_SET,
	APUR_SET_GENERAL_ACC_LED_SET,
	APUR_SET_GENERAL_PARKING_DETECT_MODE,
	APUR_SET_GENERAL_ORIGINAL_ANTENNA_SUPPLY,
	APUR_SET_GENERAL_ANTI_THEFT_SET,
	APUR_SET_GENERAL_ANTENNA_GAIN_SET
}enumApurSettingGeneral;

#endif


