/*
** ###################################################################
**     This code is generated by the Device Initialization Tool.
**     It is overwritten during code generation.
**     USER MODIFICATION ARE NOT PRESERVED IN THIS FILE.
**
**     Project   : BYD_COM_FLASH_WRITE
**     Processor : MC9S08DZ60CLH
**     Version   : Bean 01.072, Driver 01.04, CPU db: 3.00.001
**     Datasheet : MC9S08DZ60 Rev. 3 10/2007
**     Date/Time : 2012-4-26, 10:19
**     Abstract  :
**         This module contains device initialization code 
**         for selected on-chip peripherals.
**     Contents  :
**         Function "MCU_init" initializes selected peripherals
**
**     (c) Copyright UNIS, spol. s r.o. 1997-2008
**     UNIS, spol. s r.o.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
** ###################################################################
*/

#ifndef __BYD_COM_FLASH_WRITE_H
#define __BYD_COM_FLASH_WRITE_H 1

/* Include shared modules, which are used for whole project */


/* User declarations and definitions */
/*   Code, declarations and definitions here will be preserved during code generation */
/* End of user declarations and definitions */

extern void MCU_init(void);
/*
** ===================================================================
**     Method      :  MCU_init (bean MC9S08DZ60_64)
**
**     Description :
**         Device initialization code for selected peripherals.
** ===================================================================
*/



__interrupt void isrVsci1tx(void);
/*
** ===================================================================
**     Interrupt handler : isrVsci1tx
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/



__interrupt void isrVsci1rx(void);
/*
** ===================================================================
**     Interrupt handler : isrVsci1rx
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/



__interrupt void isrVsci1err(void);
/*
** ===================================================================
**     Interrupt handler : isrVsci1err
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/



__interrupt void isrVtpm1ovf(void);
/*
** ===================================================================
**     Interrupt handler : isrVtpm1ovf
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/






/* END BYD_COM_FLASH_WRITE */

#endif
/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 3.03 [04.07]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
